# GraphQL Schema

type Query {
  """
  Получить клиента по идентификатору.
  Включает в себя возможность запроса связанных документов и родственников.
  Заменяет собой несколько REST-ендпоинтов.
  """
  client(
    "Уникальный идентификатор клиента"
    id: ID!
  ): Client
}

"""
Сущность 'Клиент'
"""
type Client {
  "ID клиента"
  id: ID!
  "Имя клиента"
  name: String!
  "Возраст клиента"
  age: Int!
  "Список документов клиента"
  documents: [Document!]
  "Список родственников клиента"
  relatives: [Relative!]
}

"""
Сущность 'Документ'
"""
type Document {
  "ID документа"
  id: ID!
  "Тип документа (паспорт, водительские права)"
  type: String!
  "Номер документа"
  number: String!
  "Дата выдачи в формате ISO 8601"
  issueDate: String!
  "Дата окончания действия (опционально)"
  expiryDate: String
}

"""
Сущность 'Родственник'
"""
type Relative {
  "ID родственника"
  id: ID!
  "Тип родственной связи (супруг/супруга, ребенок, etc.)"
  relationType: String!
  "Имя родственника"
  name: String!
  "Возраст родственника"
  age: Int
}